sudo: required
services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_011c5f4a1666_key -iv $encrypted_011c5f4a1666_iv
    -in signingKey.pem.enc -out keys/signingKey.pem -d
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu
    $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

before_script:
  - sed -i 's/$MONGOUSER/'$MONGO_USER'/g' Dockerfile
  - sed -i 's/$MONGOPASS/'$MONGO_PASS'/g' Dockerfile
  - sed -i 's/$MONGOHOST/'$MONGO_HOST'/g' Dockerfile
  - sed -i 's/$MONGOPORT/'$MONGO_PORT'/g' Dockerfile
  - sed -i 's/$MONGODB/'$MONGO_DB'/g' Dockerfile
  - sed -i 's/$TWILIO/'$TWILIO_PRIVATE'/g' Dockerfile
  - sudo apt-get -y install qemu-user-static
  - docker run --rm --privileged multiarch/qemu-user-static:register
script:
  - docker build -t reg.dispatch.sh/maartje/lgu-backend.dispatch.sh ./
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    reg.dispatch.sh; docker push reg.dispatch.sh/maartje/lgu-backend.dispatch.sh; fi
